### ISSUE TITLE
不能动态修改AUTHORITY ？

### ISSUE THREAD

**Issue by ruijun** [DozenWang/DPreference#1]
@DozenWang 

你好，为什么不提供接口来动态修改`PreferenceProvider AUTHORITY`的值呢？如果不同的应用都使用了`DPreference`，不会出现安装冲突的问题？

**Comment by DozenWang** [comment]
@ruijun 在配置AndroidManifest.xml 声明自己的authority 就可以了，DPreference 没有提供接口
